spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.database.port=${SPRING_DATABASE_PORT}


jwt.secret=${JWT_SECRET}

spring.jpa.open-in-view=false
spring.datasource.driver-class-name=org.postgresql.Driver

app.frontend.ur1=${EMAIL_URL}
resend.api.key=${MAIL_PASSWORD}
